version: 0.2

phases:
  install:
    commands:
      - pip install awscli  # Optional, only if not installed
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - cd frontend/ayurastra
      - npm install
      - cd ..
      - cd ..

  build:
    commands:
      - cd backend
      - echo "Building the application..."
      - python manage.py migrate
      - python manage.py makemigrations
      - cd ..
      - cd frontend/ayurastra
      - npm run build

  post_build:
    commands:
      - echo "Post-build actions..."

  artifacts:
    files:
      - backend.zip  # Package your backend application for deployment
    base-directory: backend  # Specify where the artifacts are located


  cache:
    paths:
      - /root/.cache/pip