version: 0.2

phases:
  install:
    commands:
      - pip install awscli  # Optional, only if not installed
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - cd frontend/ayurastra
      - npm install
      - cd ..
      - cd ..

  build:
    commands:
      - cd backend
      - echo "Building the application..."
      - python manage.py migrate
      - python manage.py makemigrations
      - cd ..
      - cd frontend/ayurastra
      - npm run build
      - cd ..
      - cd ..

  post_build:
    commands:
      - echo "Post-build actions..."
      
artifacts:
  files:
    - '**/*'  # Include everything from the build output
  base-directory: frontend/ayurastra/dist  # Specify where the files are generated after the build process
  discard-paths: yes
