version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - cd frontend/ayurastra
      - npm install
      - cd ..
      - cd ..

  build:
    commands:
      - cd backend
      - echo "Building the application..."
      - python manage.py migrate
      - python manage.py makemigrations
      - cd ..
      - cd frontend/ayurastra
      - npm run build

  post_build:
    commands:
      - echo "Post-build actions..."

artifacts:
  files:
    - '**/*'
