version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - npm install

  build:
    commands:
      - echo "Building the application..."
      - python manage.py migrate
      - python manage.py collectstatic --noinput
      - npm run build

  post_build:
    commands:
      - echo "Post-build actions..."

artifacts:
  files:
    - '**/*'
