version: 0.2

phases:
  install:
    commands:
      - cd backend
      - pip install -r requirements.txt
      - cd ../frontend
      - npm install

  build:
    commands:
      - cd backend
      - python manage.py migrate
      - python manage.py collectstatic --noinput
      - cd ../frontend
      - npm run build

  post_build:
    commands:
      aws s3 cp frontend/ayurastra/dist https://us-east-1.console.aws.amazon.com/s3/buckets/mydevopstestbucket?region=us-east-1&bucketType=general --recursive --profile my-profile

artifacts:
  files:
    - backend.zip
  base-directory: backend

cache:
  paths:
    - /root/.cache/pip
    - /root/.npm